language: r
cache: packages

r_packages: covr

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
    - libudunits2-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - libv8-dev
    - netcdf-bin

after_success:
  - Rscript -e 'covr::codecov()'

env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - _R_CHECK_FORCE_SUGGESTS_=FALSE

notifications:
  email:
    on_success: never
    on_failure: never
